# -*- coding: utf-8 -*-
"""trata.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gFqWvkYGsf_maTRluwDoG89_YvTQJRN5
"""

from google.colab import drive
drive.mount('/content/gdrive')

import matplotlib.pyplot as plt
import pandas as pd 
import numpy as np
from sklearn.cluster import AgglomerativeClustering
import scipy.cluster.hierarchy as sch


path = '/content/gdrive/My Drive/Colab Notebooks/folium/Informaci_n_Lugar_de_origen_casos_de_Trata_de_Personas_Externa.csv'
df = pd.read_csv(path, header=None)
df2 = df
df2["total for year"] = df.sum(axis = 1)
df1 = df.T
X = df.iloc[1:36,1:8].to_numpy()
labels = list(df.iloc[1:36,0])
sizes = list(df2.iloc[1:36,8])
sizes_min = []
label_min = []
for i in range(0,len(sizes)):
  if sizes[i] > 20 :
    sizes_min.append(sizes[i])
    label_min.append(labels[i])
model = AgglomerativeClustering(n_clusters=4, affinity='euclidean', linkage='ward')
model.fit(X)
labels_ = model.labels_
fig = plt.figure(figsize=(20, 13))
plt.subplot(2, 2, 1)
explode = (0, 0.1, 0, 0, 0, 0.1) 
labels = list(df.iloc[1:36,0])
sizes = list(df2.iloc[1:36,8])
plt.pie(sizes_min,labels=label_min,explode = explode , autopct='%1.1f%%', shadow=True, startangle=140,
        wedgeprops=dict(width=0.6, edgecolor='w'))

plt.axis('equal')

plt.subplot(2, 2, 2)
for i in range(1,35):
  if df.iloc[1:36,8][i] > 20:
    plt.plot(df1.iloc[1:8,0], df1.iloc[1:8,i], 'o-', label=df.iloc[1:36,0][i])
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0.)
    plt.ylabel('People')
    plt.xlabel('Year')
    plt.title("trend of human trafficking for years")

plt.subplot(2, 2, 3)
plt.plot(df1.iloc[1:8,0], df1.iloc[1:8,36], 'o-', color = "black")
plt.ylabel('People')
plt.xlabel('Year')
plt.title("trend of human trafficking for years in all Colombia")

plt.subplot(2, 2, 4)
for i in range(0,len(labels_)):
  if labels_[i] == 0:
    plt.scatter(df1.iloc[1:8,0].to_numpy(), X[i,::], s=50, marker='o', color='red')
  if labels_[i] == 1:
    plt.scatter(df1.iloc[1:8,0].to_numpy(), X[i,::], s=50, marker='o', color='blue')
  if labels_[i] == 2:
    plt.scatter(df1.iloc[1:8,0].to_numpy(), X[i,::], s=50, marker='o', color='green')
  if labels_[i] == 3:
    plt.scatter(df1.iloc[1:8,0].to_numpy(), X[i,::], s=50, marker='o', color='black')
plt.ylabel('People')
plt.xlabel('Year')
plt.title("AgglomerativeClustering - linkage = Warm")

fig.savefig('/content/gdrive/My Drive/Colab Notebooks/folium/trata_ext.png')
plt.show()

